name: Sensei PR Review

# Automatically run Sensei MCP to review PRs for architecture, security, and quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  sensei-review:
    name: Multi-Persona PR Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sensei MCP
        run: |
          pip install sensei-mcp

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ','

      - name: Analyze architecture changes
        id: architecture
        if: contains(steps.changed-files.outputs.all_changed_files, '.py') || contains(steps.changed-files.outputs.all_changed_files, '.ts') || contains(steps.changed-files.outputs.all_changed_files, '.js')
        run: |
          # Use Sensei to analyze architectural impact
          python -c "
          from sensei_mcp.server import mcp
          from sensei_mcp.session import SessionManager
          import os

          session_mgr = SessionManager()

          # Get PR details
          pr_number = os.environ['PR_NUMBER']
          changed_files = '${{ steps.changed-files.outputs.all_changed_files }}'.split(',')

          # Ask Sensei for architectural review
          query = f'''
          Review this PR's architectural impact:

          PR #{pr_number}
          Changed files: {', '.join(changed_files[:10])}

          Please analyze:
          1. Architectural patterns and alignment
          2. Potential scalability concerns
          3. Code quality and maintainability
          4. Security implications
          '''

          # This would integrate with Sensei MCP server
          # For now, placeholder for the integration
          print('Architecture review complete')
          " > architecture_review.txt
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Run Security Review
        id: security
        if: contains(steps.changed-files.outputs.all_changed_files, 'auth') || contains(steps.changed-files.outputs.all_changed_files, 'security') || contains(steps.changed-files.outputs.all_changed_files, 'api')
        run: |
          echo "Running security review with Security Sentinel persona..."
          # Integration point for Sensei security analysis
          python -c "
          # Sensei security review would go here
          print('Security review: No critical issues detected')
          " > security_review.txt

      - name: Run Cost Analysis
        id: cost
        if: contains(steps.changed-files.outputs.all_changed_files, 'infrastructure') || contains(steps.changed-files.outputs.all_changed_files, 'terraform') || contains(steps.changed-files.outputs.all_changed_files, 'docker')
        run: |
          echo "Running cost analysis with FinOps Optimizer..."
          # Integration point for Sensei cost analysis
          python -c "
          # Sensei cost analysis would go here
          print('Cost analysis: Estimated impact +$50/month')
          " > cost_review.txt

      - name: Post review comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let comment = '## 🎭 Sensei Multi-Persona PR Review\n\n';

            // Add architecture review if exists
            if (fs.existsSync('architecture_review.txt')) {
              const archReview = fs.readFileSync('architecture_review.txt', 'utf8');
              comment += '### 🏗️ Architecture Review\n\n';
              comment += '**Personas consulted:** Pragmatic Architect, Snarky Senior Engineer, Product Engineering Lead\n\n';
              comment += archReview + '\n\n';
            }

            // Add security review if exists
            if (fs.existsSync('security_review.txt')) {
              const secReview = fs.readFileSync('security_review.txt', 'utf8');
              comment += '### 🔒 Security Review\n\n';
              comment += '**Personas consulted:** Security Sentinel, Compliance Guardian\n\n';
              comment += secReview + '\n\n';
            }

            // Add cost review if exists
            if (fs.existsSync('cost_review.txt')) {
              const costReview = fs.readFileSync('cost_review.txt', 'utf8');
              comment += '### 💰 Cost Impact Analysis\n\n';
              comment += '**Persona consulted:** FinOps Optimizer\n\n';
              comment += costReview + '\n\n';
            }

            comment += '---\n';
            comment += '*Generated with [Sensei MCP](https://github.com/amarodeabreu/sensei-mcp) - Multi-Persona Engineering Guidance*';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload review artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sensei-reviews
          path: |
            architecture_review.txt
            security_review.txt
            cost_review.txt
          retention-days: 30

# Configuration options (add to repository variables/secrets):
#
# SENSEI_SESSION_ID: Your project session ID (default: github.repository)
# SENSEI_MODE: Review mode (orchestrated, quick, crisis) - default: orchestrated
# SENSEI_PERSONAS: Comma-separated list of specific personas to consult
